### ISSUE TITLE
Incorrect pathnames cause failure to run

### ISSUE THREAD

**Issue by phptek** [chillu/phpmd-silverstripe#1]
If you try and run with `all.xml` you'll get an error that phpmd cannot find `silverstripe.xml`. This is resolved either by changing the vendor/chillu/silverstripe-phpmd/Rulesets dir to be "rulesets" as specified in all.xml, or capitalise the dirname in all.xml.

Additionally, once this is fixed, a missing "cleancode.xml" file will cause a similar error as will all the others.

Running with silverstripe.xml directly of course works A-OK.

**Comment by chillu** [comment]
Has d130d0e5f99f02326354587740232190de4c3408 fixed it for you? You'll need to git clone the repo, `composer global require` will only install tagged releases by default.

**Comment by phptek** [comment]
Fixed, closing.
